import type { AdminUser } from "./api";

/**
 * All granular permission keys used across the admin dashboard.
 * Permissions are resolved from active backend Role records.
 * Only the explicit SUPER_ADMIN role key bypasses individual checks.
 */
export const ALL_PERMISSIONS = [
  "staff.view", "staff.create", "staff.edit", "staff.suspend", "staff.revoke_sessions",
  "roles.view", "roles.manage",
  "states.view", "states.manage",
  "cities.view", "cities.manage",
  "zones.view", "zones.manage",
  "markets.view", "markets.manage", "markets.assign_hub",
  "hubs.view", "hubs.manage", "hubs.assign_markets",
  "categories.view", "categories.manage",
  "partners.view", "partners.manage",
  "runners.manage", "runners.assign",
  "audit.view", "settings.manage",
  "orders.view",
  "orders.edit",
  "orders.cancel",
  "orders.create",
  "products.view",
  "products.review",
  "products.edit",
  "catalog.submission.view",
  "catalog.submission.review",
  "catalog.submission.request_changes",
  "catalog.submission.approve",
  "catalog.submission.reject",
  "catalog.product.view",
  "catalog.product.edit",
  "catalog.product.publish",
  "catalog.product.pause",
  "catalog.product.unpublish",
  "catalog.pricing.view_internal",
  "catalog.pricing.edit",
  "catalog.negotiation_rules.view_internal",
  "catalog.negotiation_rules.edit",
  "catalog.media.upload",
  "catalog.media.review",
  "customers.view",
  "customers.edit",
  "runners.view",
  "fulfilment.view", "fulfilment.manage", "fulfilment.assign", "fulfilment.consolidate",
  "fulfilment.hub.view", "fulfilment.hub.receive", "fulfilment.hub.qc",
  "logistics.view", "logistics.book", "logistics.manage", "logistics.track",
  "returns.view", "returns.review", "returns.manage",
  "custody.view", "custody.manage",
  "finance.refunds.view", "finance.refunds.process",
  "commerce.pod.review", "commerce.pod.override", "commerce.pod.eligibility",
  "commerce.payments.view", "commerce.payments.reconcile",
  "commerce.outbox.view", "commerce.settings.view", "commerce.settings.manage",
  "financials.view",
  "financials.refund",
  "financials.reconcile",
  "refunds.view",
  "refunds.manage",
  "deletions.view",
  "deletions.manage",
  "reports.view",
  "ai_negotiation.view",
  "app_releases.view", "app_releases.manage",
  "ai_negotiation.manage",
  "ai_negotiation.transcript.view",
  "settings.view",
  "delivery.coverage.view", "delivery.coverage.manage",
  "delivery.pricing.view", "delivery.pricing.manage", "delivery.pricing.preview",
  "market.vendors.view", "market.vendors.manage", "market.vendors.invite",
  "market.collections.view", "market.collections.manage",
  "market.payments.view", "market.payments.reconcile",
  "catalog.availability.view", "catalog.availability.manage", "catalog.availability.confirm",
  "coupons.view", "coupons.manage",
  "credits.view", "credits.adjust",
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

export const PERMISSION_LABELS: Record<Permission, string> = {
  "staff.view": "View Staff", "staff.create": "Create Staff", "staff.edit": "Edit Staff",
  "staff.suspend": "Suspend Staff", "staff.revoke_sessions": "Revoke Staff Sessions",
  "roles.view": "View Roles", "roles.manage": "Manage Roles",
  "states.view": "View States", "states.manage": "Manage States",
  "cities.view": "View Cities", "cities.manage": "Manage Cities",
  "zones.view": "View Zones", "zones.manage": "Manage Zones",
  "markets.view": "View Markets", "markets.manage": "Manage Markets", "markets.assign_hub": "Assign Market Hubs",
  "hubs.view": "View Hubs", "hubs.manage": "Manage Hubs", "hubs.assign_markets": "Assign Hub Markets",
  "categories.view": "View Categories", "categories.manage": "Manage Categories",
  "partners.view": "View Partners", "partners.manage": "Manage Partners",
  "runners.manage": "Manage Market Associates", "runners.assign": "Assign Market Associates",
  "audit.view": "View Audit Logs", "settings.manage": "Manage Settings",
  "orders.view": "View Orders",
  "orders.edit": "Edit Orders",
  "orders.cancel": "Cancel Orders",
  "orders.create": "Create Orders",
  "products.view": "View Products",
  "products.review": "Review Products",
  "products.edit": "Edit Products",
  "catalog.submission.view": "View Catalog Submissions",
  "catalog.submission.review": "Review Catalog Submissions",
  "catalog.submission.request_changes": "Request Catalog Changes",
  "catalog.submission.approve": "Approve Catalog Submissions",
  "catalog.submission.reject": "Reject Catalog Submissions",
  "catalog.product.view": "View Commercial Catalog",
  "catalog.product.edit": "Edit Commercial Products",
  "catalog.product.publish": "Publish Commercial Products",
  "catalog.product.pause": "Pause Commercial Products",
  "catalog.product.unpublish": "Unpublish Commercial Products",
  "catalog.pricing.view_internal": "View Internal Pricing",
  "catalog.pricing.edit": "Edit Catalog Pricing",
  "catalog.negotiation_rules.view_internal": "View Negotiation Rules",
  "catalog.negotiation_rules.edit": "Edit Negotiation Rules",
  "catalog.media.upload": "Upload Catalog Media",
  "catalog.media.review": "Review Catalog Media",
  "customers.view": "View Customers",
  "customers.edit": "Edit Customers",
  "runners.view": "View Market Associates",
  "fulfilment.view": "View Fulfilment",
  "fulfilment.manage": "Manage Fulfilment",
  "fulfilment.assign": "Assign Fulfilment",
  "fulfilment.consolidate": "Consolidate Orders",
  "fulfilment.hub.view": "View Hub Packages",
  "fulfilment.hub.receive": "Receive Hub Packages",
  "fulfilment.hub.qc": "Perform Hub Quality Checks",
  "logistics.view": "View Shipments",
  "logistics.book": "Book Shipments",
  "logistics.manage": "Manage Shipments",
  "logistics.track": "Track Shipments",
  "returns.view": "View Returns",
  "returns.review": "Review Returns",
  "returns.manage": "Manage Returns",
  "custody.view": "View Partner Custody",
  "custody.manage": "Manage Partner Custody",
  "finance.refunds.view": "View Fulfilment Refunds",
  "finance.refunds.process": "Process Fulfilment Refunds",
  "commerce.pod.review": "Review Pay-at-Handover Orders",
  "commerce.pod.override": "Override Pay-at-Handover Limits",
  "commerce.pod.eligibility": "Manage Customer Pay-at-Handover Eligibility",
  "commerce.payments.view": "View Commerce Payments",
  "commerce.payments.reconcile": "Reconcile Commerce Payments",
  "commerce.outbox.view": "View Commerce Events",
  "commerce.settings.view": "View Commerce Settings",
  "commerce.settings.manage": "Manage Commerce Settings",
  "financials.view": "View Financials",
  "financials.refund": "Issue Refunds",
  "financials.reconcile": "Reconcile Payments",
  "refunds.view": "View Refunds",
  "refunds.manage": "Manage Refunds",
  "deletions.view": "View Deletion Requests",
  "deletions.manage": "Manage Deletion Requests",
  "reports.view": "View Reports",
  "ai_negotiation.view": "View AI Negotiation",
  "app_releases.view": "View App Releases",
  "app_releases.manage": "Manage App Releases",
  "ai_negotiation.manage": "Manage AI Negotiation",
  "ai_negotiation.transcript.view": "View Negotiation Transcripts",
  "settings.view": "View Settings",
  "delivery.coverage.view": "View Delivery Coverage",
  "delivery.coverage.manage": "Manage Delivery Coverage",
  "delivery.pricing.view": "View Delivery Pricing",
  "delivery.pricing.manage": "Manage Delivery Pricing",
  "delivery.pricing.preview": "Preview Delivery Pricing",
  "market.vendors.view": "View Market Suppliers",
  "market.vendors.manage": "Manage Market Suppliers",
  "market.vendors.invite": "Invite Market Suppliers",
  "market.collections.view": "View Supplier Collections",
  "market.collections.manage": "Manage Supplier Collections",
  "market.payments.view": "View Supplier Payment Status",
  "market.payments.reconcile": "Reconcile Supplier Payments",
  "catalog.availability.view": "View Availability Checks",
  "catalog.availability.manage": "Request Availability Checks",
  "catalog.availability.confirm": "Confirm Product Availability",
  "coupons.view": "View Coupons",
  "coupons.manage": "Manage Coupons",
  "credits.view": "View Customer Credits",
  "credits.adjust": "Adjust Customer Credits",
};

export const PERMISSION_GROUPS: { label: string; permissions: Permission[] }[] = [
  {
    label: "Orders",
    permissions: ["orders.view", "orders.edit", "orders.create", "orders.cancel"],
  },
  {
    label: "Catalog",
    permissions: [
      "products.view", "products.review", "products.edit",
      "categories.view", "categories.manage",
      "catalog.submission.view", "catalog.submission.review", "catalog.submission.request_changes",
      "catalog.submission.approve", "catalog.submission.reject", "catalog.product.view",
      "catalog.product.edit", "catalog.product.publish", "catalog.product.pause",
      "catalog.product.unpublish", "catalog.pricing.view_internal", "catalog.pricing.edit",
      "catalog.negotiation_rules.view_internal", "catalog.negotiation_rules.edit",
      "catalog.media.upload", "catalog.media.review",
    ],
  },
  {
    label: "Customers",
    permissions: ["customers.view", "customers.edit"],
  },
  {
    label: "Operations",
    permissions: [
      "runners.view", "runners.manage", "fulfilment.view", "fulfilment.manage",
      "fulfilment.assign", "fulfilment.consolidate",
      "fulfilment.hub.view", "fulfilment.hub.receive", "fulfilment.hub.qc",
      "logistics.view", "logistics.book", "logistics.manage", "logistics.track",
      "returns.view", "returns.review", "returns.manage", "custody.view", "custody.manage",
    ],
  },
  {
    label: "Finance & Reports",
    permissions: [
      "financials.view", "financials.refund", "financials.reconcile",
      "finance.refunds.view", "finance.refunds.process",
      "commerce.payments.view", "commerce.payments.reconcile",
      "reports.view", "ai_negotiation.view",
      "coupons.view", "coupons.manage",
      "credits.view", "credits.adjust",
    ],
  },
  {
    label: "Platform",
    permissions: [
      "refunds.view", "refunds.manage", "deletions.view", "deletions.manage",
      "commerce.pod.review", "commerce.pod.override", "commerce.pod.eligibility",
      "commerce.outbox.view", "commerce.settings.view", "commerce.settings.manage",
      "settings.view", "settings.manage",
      "delivery.coverage.view", "delivery.coverage.manage", "delivery.pricing.view", "delivery.pricing.manage", "delivery.pricing.preview",
      "market.vendors.view", "market.vendors.manage", "market.vendors.invite", "market.collections.view", "market.collections.manage",
      "market.payments.view", "market.payments.reconcile", "catalog.availability.view", "catalog.availability.manage", "catalog.availability.confirm",
    ],
  },
];

export function hasPermission(user: AdminUser | null | undefined, permission: Permission): boolean {
  if (!user) return false;
  if (user.roleKeys?.includes("SUPER_ADMIN")) return true;
  return Array.isArray(user.permissions) && user.permissions.includes(permission);
}

export function isSuperAdmin(user: AdminUser | null | undefined): boolean {
  return user?.role === "super_admin" || user?.role === "SUPER_ADMIN" || Boolean(user?.roleKeys?.includes("SUPER_ADMIN"));
}

export function isAdmin(user: AdminUser | null | undefined): boolean {
  return user?.accountType === "staff";
}
